version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network
    restart: always
    command: >
      bash -c "mkdir -p /app/data && touch /app/data/db.sqlite3 && chmod 666 /app/data/db.sqlite3 && python -m flask run --host=0.0.0.0"

  main:
    build:
      context: ./backend
      dockerfile: Dockerfile.main
    volumes:
      - ./backend/data:/app/data
    networks:
      - app-network
    depends_on:
      - backend
    restart: always
    command: >
      bash -c "mkdir -p /app/data && touch /app/data/db.sqlite3 && chmod 666 /app/data/db.sqlite3 && sleep 5 && cd /app/data && python /app/main.py"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - app-network
    depends_on:
      - backend
    restart: always
    extra_hosts:
      - "localhost:127.0.0.1"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge 